language: ruby

rvm:
- 2.1.2
- 2.1.5
- 2.2.0

before_install:
  # TODO: Newer versions of rubygems on Travis CI fail on RSpec (see http://stackoverflow.com/a/33800008/4630536). Remove the forced rubygems version when this is fixed.
  - gem update --system 2.4.8
  - gem --version

deploy:
  provider: rubygems
  api_key:
    secure: kwPTUQGR25urq/yKIFLcV2TjBalTGU5uWI+jK36I1fatvtbk6geL3BbpPuyiIQOvu2Kge6c5bEQpnOFNNeRW08G7vojhn1aFp7MtKLuE47jazbA1ekGh7Cvyt/actu9wensNAuew87IpJW9Fjxu+5B/RHz678nJqIA4zxFwL1TU=
  gem: metasploit-runner
  on:
    tags: true
    repo: amngibson/metasploit-runner
    all_branches: true
